[phases.setup]
nixPkgs = ["python3", "gcc", "gcc.libc", "gcc.libc.dev", "gcc.libc.static"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm rebuild better-sqlite3 --build-from-source"]

[start]
cmd = "npm start"
